name: CI
on:
  pull_request: {}
jobs:
  prod-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo "${{ github.head_ref }}"
